### ISSUE TITLE
Error occurred when cross tenant try to access dashboard settings

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1047]
**Description:**
If dashboard ownership is shared among the cross tenant users by applying scope "apim_analytics:admin_any" there will be an error in the terminal when tenant users try to access dashboard settings.

This is due to the associate roles of scope is not available in other tenants. This use case is not supported ATM and incorrect as for now. Hence we can ignore the issue. But better to fix and handle the exceptions. 

```
..................................
[2020-03-10 10:49:08,291]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.NullPointerException
	at org.wso2.carbon.analytics.permissions.internal.impl.DefaultPermissionProvider.lambda$getGrantedRolesOfTenant$1(DefaultPermissionProvider.java:273)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.analytics.permissions.internal.impl.DefaultPermissionProvider.getGrantedRolesOfTenant(DefaultPermissionProvider.java:273)
	at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.getDashboardRoles(DashboardMetadataProviderImpl.java:274)
	at org.wso2.carbon.dashboards.api.internal.DashboardRestApi.getDashboardRoles(DashboardRestApi.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$47(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ruks** [comment]
Closing the issue since SP analytics is deprecated.
