### ISSUE TITLE
[2.5] [DB2]Errors when the server tries to create tables in STAT DB at the startup.

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/analytics-apim#1141]
**Description:**

Errors at the server startup when the analytics server is trying to create tables required in STAT DB. There are errors similar to [1] when the table creating scripts are executed. As per the error code printed , the doc [2] suggest that the error may be due to primary key or a unique constraint is too long or two many columns than whats allowed in the default table space of DB2. The same error code can be observed on multiple tables.

**Affected Product Version:**
APIM 2.5

**OS, DB, other environment details and versions:**    
DB2 11.5

[1]-  ERROR {org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService} -  Error while executing query :         create temporary table APIRequestSummaryData using CarbonJDBC options (dataSource "WSO2AM_STATS_DB", tableName "API_REQUEST_SUMMARY",    schema "api STRING ,    api_version STRING ,    version STRING ,    apiPublisher STRING ,    consumerKey STRING ,    userId STRING ,    context STRING ,    max_request_time LONG ,    total_request_count INTEGER ,    hostName STRING ,    year INTEGER ,    month INTEGER ,    day INTEGER ,    time STRING",    primaryKeys "api,api_version,version,apiPublisher,consumerKey,userId,context,hostName,year,month,day"    )
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query create temporary table APIRequestSummaryData using CarbonJDBC options (dataSource "WSO2AM_STATS_DB", tableName "API_REQUEST_SUMMARY",    schema "api STRING ,    api_version STRING ,    version STRING ,    apiPublisher STRING ,    consumerKey STRING ,    userId STRING ,    context STRING ,    max_request_time LONG ,    total_request_count INTEGER ,    hostName STRING ,    year INTEGER ,    month INTEGER ,    day INTEGER ,    time STRING",    primaryKeys "api,api_version,version,apiPublisher,consumerKey,userId,context,hostName,year,month,day"    )
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:911)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:868)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:256)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:206)
	at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:60)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error while creating table 'API_REQUEST_SUMMARY' in WSO2AM_STATS_DB: DB2 SQL Error: SQLCODE=-613, SQLSTATE=54008, SQLERRMC=API..., DRIVER=4.26.14
	at org.apache.spark.sql.jdbc.carbon.AnalyticsJDBCRelationProvider.createRelation(JDBCRelation.scala:133)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.execution.datasources.CreateTempTableUsing.run(ddl.scala:92)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
	at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:52)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:907)
	... 11 more
Caused by: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Error while creating table 'API_REQUEST_SUMMARY' in WSO2AM_STATS_DB: DB2 SQL Error: SQLCODE=-613, SQLSTATE=54008, SQLERRMC=API..., DRIVER=4.26.14
	at org.apache.spark.sql.jdbc.carbon.CarbonJDBCUtils$.checkAndCreateTable(CarbonJDBCUtils.scala:114)
	at org.apache.spark.sql.jdbc.carbon.AnalyticsJDBCRelationProvider.createRelation(JDBCRelation.scala:128)
	... 27 more
Caused by: com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-613, SQLSTATE=54008, SQLERRMC=API..., DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:815)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)

[2]- [https://www.sqlerror.de/db2_sql_error_-613_sqlstate_54008.html](https://www.sqlerror.de/db2_sql_error_-613_sqlstate_54008.html)

**Comment by ruks** [comment]
This is fixed and works in APIM 300 onwards. Hence closing.
