### ISSUE TITLE
APIM-analytics-2.6.0 dashboard /portal Errors

### ISSUE THREAD

**Issue by Kalpanayella** [wso2/analytics-apim#1261]
**Description:**

We are seeing http.netty errors when trying to access APIM-analytics 2.6.0  dashboard using url : https://localhost:9643/portal 

Also seeing the same with APIM analytics latest updated version downloaded from wum : ( wso2am-analytics-2.6.0+1591343037184.full.zip ) :

```
2020-06-29 19:47:14,886] ERROR {org.wso2.transport.http.netty.common.Util} - Remote client closed the connection before completing outbound response java.io.IOException: Remote client closed the connection before completing outbound response
	at org.wso2.transport.http.netty.common.Util.lambda$checkForResponseWriteStatus$2(Util.java:627)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at org.wso2.transport.http.netty.common.Util.checkForResponseWriteStatus(Util.java:623)
	at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.writeOutboundResponseBody(HttpOutboundRespListener.java:194)
	at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.writeOutboundResponse(HttpOutboundRespListener.java:142)
	at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.lambda$null$0(HttpOutboundRespListener.java:94)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Product Version:**
wso2am-analytics-2.6.0
wso2am-analytics-2.6.0+1591343037184.full.zip

**OS, DB, other environment details and versions:**    
This is the same behavior observed on MacOs catalina 10.15.5 , CentOS 7 and Windows  too.

**Steps to reproduce:**
1. Start APIM-Analytics server version 2.6.0 . (Navigate APIM_analytics_home/bin and execute `sh worker.sh`)
2. Start API manager server version 2.6.0 . (Navigate APIM_home/bin and execute `sh wso2server.sh`)
3. Initialize Dashboard node  (Navigate APIM_analytics_home/bin and execute `sh dashboard.sh`), once started click on https://localhost:9643/portal or https://{local host IP}:9643/portal and you'll see errors mentioned above.

**Comment by ruks** [comment]
APIM Analytics 300 onwards, dashboards are served on https://localhost:9643/analytics-dashboard and https://localhost:9643/portal is no longer available. Hence closing the issue. 

APIM and Analytics 2.6.0 dashboards are provided in APIM portals and have to use them. Above use, the case is not tested with APIM analytics 2.6.0. If there is custom use case and required custom dashboards it should be supported with wso2 SP 4.3.0.
