### ISSUE TITLE
Dashboard startup error with h2 DB

### ISSUE THREAD

**Issue by ruks** [wso2/analytics-apim#1311]
**Description:**
Noticed the following issue when the dashboard is start before the APIM. This is due to the h2 DB driver mismatch between APIM and Analytics. If APIM starts first this issue not happening. But if dashboard start first H2 DB file intimidation get failed and DB file gets corrupted. 

This need be in https://github.com/wso2/carbon-metrics by upgrading H2 version.
```
[2020-07-07 01:39:38,547] ERROR {org.wso2.carbon.datasource.rdbms.hikari.HikariRDBMSDataSource} - Cannot connect to JDBC URL jdbc:h2:/Users/rukshan/wso2/apim/3.2.0/beta/wso2am-analytics-3.2.0-SNAPSHOT/../wso2am-3.2.0-beta/repository/database/WSO2AM_DB;AUTO_SERVER=TRUE. Failed due to Failed to initialize pool: Syntax error in SQL statement "CREATE CACHED TABLE ""PUBLIC"".""AM_GW_API_ARTIFACTS""(
    ""API_ID"" VARCHAR(255) NOT NULL,
    ""ARTIFACT"" BLOB,
    ""GATEWAY_INSTRUCTION"" VARCHAR(20),
    ""GATEWAY_LABEL"" VARCHAR(255) NOT NULL,
    ""TIME_STAMP"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP NOT NULL
)"; expected "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."AM_GW_API_ARTIFACTS"(
    "API_ID" VARCHAR(255) NOT NULL,
    "ARTIFACT" BLOB,
    "GATEWAY_INSTRUCTION" VARCHAR(20),
    "GATEWAY_LABEL" VARCHAR(255) NOT NULL,
    "TIME_STAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) [42001-196]retrying in 5 seconds com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Syntax error in SQL statement "CREATE CACHED TABLE ""PUBLIC"".""AM_GW_API_ARTIFACTS""(
    ""API_ID"" VARCHAR(255) NOT NULL,
    ""ARTIFACT"" BLOB,
    ""GATEWAY_INSTRUCTION"" VARCHAR(20),
    ""GATEWAY_LABEL"" VARCHAR(255) NOT NULL,
    ""TIME_STAMP"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP NOT NULL
)"; expected "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."AM_GW_API_ARTIFACTS"(
    "API_ID" VARCHAR(255) NOT NULL,
    "ARTIFACT" BLOB,
    "GATEWAY_INSTRUCTION" VARCHAR(20),
    "GATEWAY_LABEL" VARCHAR(255) NOT NULL,
    "TIME_STAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) [42001-196]
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariRDBMSDataSource.getDataSource(HikariRDBMSDataSource.java:61)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariDataSourceReader.createDataSource(HikariDataSourceReader.java:74)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:79)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:60)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildCarbonDataSource(DataSourceBuilder.java:44)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:163)
	at org.wso2.carbon.datasource.core.internal.DataSourceListenerComponent.onAllRequiredCapabilitiesAvailable(DataSourceListenerComponent.java:125)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE CACHED TABLE ""PUBLIC"".""AM_GW_API_ARTIFACTS""(
    ""API_ID"" VARCHAR(255) NOT NULL,
    ""ARTIFACT"" BLOB,
    ""GATEWAY_INSTRUCTION"" VARCHAR(20),
    ""GATEWAY_LABEL"" VARCHAR(255) NOT NULL,
    ""TIME_STAMP"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP NOT NULL
)"; expected "(, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."AM_GW_API_ARTIFACTS"(
    "API_ID" VARCHAR(255) NOT NULL,
    "ARTIFACT" BLOB,
    "GATEWAY_INSTRUCTION" VARCHAR(20),
    "GATEWAY_LABEL" VARCHAR(255) NOT NULL,
    "TIME_STAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) [42001-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.getSyntaxError(DbException.java:205)
	at org.h2.command.Parser.getSyntaxError(Parser.java:541)
	at org.h2.command.Parser.read(Parser.java:3258)
	at org.h2.command.Parser.readIfMore(Parser.java:894)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6234)
	at org.h2.command.Parser.parseCreate(Parser.java:4351)
	at org.h2.command.Parser.parsePrepared(Parser.java:366)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:297)
	at org.h2.command.Parser.prepare(Parser.java:242)
	at org.h2.engine.Session.prepare(Session.java:543)
	at org.h2.engine.Session.prepare(Session.java:530)
	at org.h2.engine.MetaRecord.execute(MetaRecord.java:56)
	at org.h2.engine.Database.open(Database.java:763)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	... 15 more
```

**Comment by ruks** [comment]
@jaadds @TanyaM FYI

**Comment by TanyaM** [comment]
Issue seems to be unrelated with the starting order of the packs. Please see the screenshot below. 

<img width="949" alt="h2" src="https://user-images.githubusercontent.com/3957104/86718628-e6275a00-c040-11ea-96e0-2ad2bf47e730.png">

Steps followed.
1. Unzip APIM and Analytics pack inside the same folder
2. Enabled analytics in deployment.toml of APIM
3. Modify the AM_DB path in Analytics dashboard deployment.yaml
4. Start the worker profile of Analytics server
5. Start the APIM server 
6. Start the dashboard profile of Analytics server once the APIM server is completely started 
Refer the highlighted timestamps in the above screenshot. APIM server was completed starting at 10.38.42 AM and Dashboard profile was started at 10.41.38 AM ( around 3 minutes after starting APIM )

Note that these servers were not started even once, before changing the AM_DB path.

**Comment by RAVEENSR** [comment]
Before starting the worker, if you start the APIM server this error will not occur.
