### ISSUE TITLE
Primary key is too long for ApiErrorAnalysisAgg aggregation related tables in DB2.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#1342]
**Description:**
The primary key is too long for ApiErrorAnalysisAgg aggregation related tables in DB2.

When starting the APIM Analytics Worker the following error is thrown:
```
[2020-07-15 16:13:09,740] ERROR {io.siddhi.core.table.Table} - Error on 'APIM_ERROR_SUMMARY'. Failed to initialize store for table name 'ApiErrorAnalysisAgg_HOURS' Error while connecting to Table 'ApiErrorAnalysisAgg_HOURS', will retry in '5 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Failed to initialize store for table name 'ApiErrorAnalysisAgg_HOURS'
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.connect(RDBMSEventTable.java:1237)
	at io.siddhi.core.table.record.AbstractQueryableRecordTable.connectAndLoadCache(AbstractQueryableRecordTable.java:206)
	at io.siddhi.core.table.Table.connectWithRetry(Table.java:406)
	at io.siddhi.core.SiddhiAppRuntimeImpl.startWithoutSources(SiddhiAppRuntimeImpl.java:478)
	at io.siddhi.core.SiddhiAppRuntimeImpl.start(SiddhiAppRuntimeImpl.java:447)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:215)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:95)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:330)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: io.siddhi.extension.store.rdbms.exception.RDBMSTableException: Unable to initialize table 'ApiErrorAnalysisAgg_HOURS'
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.createTable(RDBMSEventTable.java:1505)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.connect(RDBMSEventTable.java:1230)
	... 20 more
Caused by: io.siddhi.extension.store.rdbms.exception.RDBMSTableException: Could not execute data definition queries for store 'ApiErrorAnalysisAgg_HOURS'
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.executeDDQueries(RDBMSEventTable.java:1558)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.createTable(RDBMSEventTable.java:1494)
	... 21 more
Caused by: com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-613, SQLSTATE=54008, SQLERRMC=AGG_TIMESTAMP..., DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:815)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k4.b(k4.java:2471)
	at com.ibm.db2.jcc.am.k4.c(k4.java:2452)
	at com.ibm.db2.jcc.t4.ab.n(ab.java:914)
	at com.ibm.db2.jcc.t4.ab.a(ab.java:120)
	at com.ibm.db2.jcc.t4.p.a(p.java:50)
	at com.ibm.db2.jcc.t4.aw.b(aw.java:220)
	at com.ibm.db2.jcc.am.k5.bm(k5.java:3599)
	at com.ibm.db2.jcc.am.k5.a(k5.java:4644)
	at com.ibm.db2.jcc.am.k5.b(k5.java:4182)
	at com.ibm.db2.jcc.am.k5.bg(k5.java:2880)
	at com.ibm.db2.jcc.am.k5.execute(k5.java:2855)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.executeDDQueries(RDBMSEventTable.java:1541)
	... 22 more
```

More about this error is included in https://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/codes/src/tpc/n613.html

The reason for this error is that the primary key created from the following aggregation is too long(which exceeds the limit).

https://github.com/wso2/analytics-apim/blob/9eadff4db08050f4c8f35554809207afd3e71c84/features/org.wso2.analytics.apim.feature/src/main/resources/siddhi-files/APIM_ERROR_SUMMARY.siddhi#L40-L49

The relevant table creation query as follows:
```
CREATE TABLE ApiErrorAnalysisAgg_HOURS (
AGG_TIMESTAMP BIGINT NOT NULL,
AGG_EVENT_TIMESTAMP BIGINT NOT NULL, 
apiName VARCHAR(254) NOT NULL, 
apiVersion VARCHAR(254) NOT NULL, 
responseCode INTEGER NOT NULL, 
apiResourceTemplate VARCHAR(254) NOT NULL, 
applicationId VARCHAR(254) NOT NULL, 
apiMethod VARCHAR(40) NOT NULL, 
applicationName VARCHAR(254) NOT NULL, 
applicationOwner VARCHAR(254) NOT NULL, 
apiCreator VARCHAR(254) NOT NULL, 
apiCreatorTenantDomain VARCHAR(254) NOT NULL, 
AGG_LAST_EVENT_TIMESTAMP BIGINT NOT NULL, 
AGG_SUM__2xx BIGINT NOT NULL, 
AGG_SUM__4xx BIGINT NOT NULL, 
AGG_SUM__5xx BIGINT NOT NULL, 
AGG_SUM_responseCount BIGINT NOT NULL, 
AGG_SUM_faultCount BIGINT NOT NULL, 
AGG_SUM_throttledCount BIGINT NOT NULL, 
PRIMARY KEY(AGG_TIMESTAMP, AGG_EVENT_TIMESTAMP, apiName, apiVersion, responseCode, apiResourceTemplate, applicationId))
```

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM Analytics 3.2.0 beta

**OS, DB, other environment details and versions:**    
mac OS Catalina 10.15.5
DB2 version 11.5

**Steps to reproduce:**
Configure APIM Analytics DB to DB2 and start the worker.

**Comment by RAVEENSR** [comment]
Fixed with https://github.com/wso2/analytics-apim/pull/1343. Hence closing the issue.
