### ISSUE TITLE
WSO2 APIM 3.2 with IS 5.10 as key manager setup have issue in multitenancy environment

### ISSUE THREAD

**Issue by sonia-petrolink** [wso2/analytics-apim#1460]
Issue - Not able to generate client credentials from /devportal under tenant
version
WSO2APIM 3.2
WSO2 IS-KM 5.10

Setup WSO2 identity server as keymanager  setup with WSO2 APIM with AM_DB,SHARED_DB

In multitenancy environment when tried to generate keys from APIM dev portal its throwing error

wso2am-3.2.0+1600181280015.full\wso2am-3.2.0\repository\tenants\1\synapse-configs\default\sequences\_throttle_out_handler_.xml
[2020-10-22 17:00:28,696]  INFO - TenantAxisUtils Loaded tenant apache.com in 28136 ms
[2020-10-22 17:01:40,638] ERROR - APIUtil Error occurred while executing SubscriberKeyMgtClient.
feign.FeignException: [302 ] during [POST] to [https://localhost:9444/t/apache.com/keymanager-operations/dcr/register] [DCRClient#createApplication(ClientInfo)]: []
        at feign.FeignException.errorStatus(FeignException.java:182) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
        at feign.FeignException.errorStatus(FeignException.java:169) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
        at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode_aroundBody0(KMClientErrorDecoder.java:34) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode(KMClientErrorDecoder.java:27) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
        at com.sun.proxy.$Proxy495.createApplication(Unknown Source) ~[?:?]
        at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.createApplication_aroundBody0(AMDefaultKeyManagerImpl.java:137) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.createApplication(AMDefaultKeyManagerImpl.java:99) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication_aroundBody8(AbstractApplicationRegistrationWorkflowExecutor.java:150) [org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication(AbstractApplicationRegistrationWorkflowExecutor.java:124) [org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.generateKeysForApplication_aroundBody6(AbstractApplicationRegistrationWorkflowExecutor.java:120) [org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.generateKeysForApplication(AbstractApplicationRegistrationWorkflowExecutor.java:117) [org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
        at org.wso2.carbon.apimgt.impl.workflow.ApplicationRegistrationSimpleWorkflowExecutor.complete_aroundBody2(ApplicationRegistrationSimpleWorkflowExecutor.java:78) [org.wso2.carbon.apimgt.impl_6.7.206.jar:?]

**Comment by isharac** [comment]
@sonia-petrolink 
1. Have you configured the IS by following the documentation [1]?  Please share your configurations in the deployment.toml 
2. Are you using APIM 3.2.0 GA released pack or the wum updated pack?

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

**Comment by sonia-petrolink** [comment]
Hi  isharac

I am using WSO2 3.2 GA released.
I am using same given document as in below email.
PFA is deployment.toml.
I copied both jar and keep it under dropping direcrory and war file under webapp.
I tried wih pure standalone IS 5.10.0 and IS-KM 5.10.0

With both same issue is there not supporting multitenancy not able to generate client credentials for tenant Application



Sonia Varshney
Senior Project Lead
Petrolink Services, Inc. | Lulu Tower Info Park | Kochi, Kerala 77092 | INDIA
Office: +04846679678 | Direct: +91 8884888270 | Cell: +91 8884888270| Fax: +04846679678
Email: sonia.varshney@petrolink.com<mailto:sonia.varshney@petrolink.com> | www.petrolink.com<http://www.petrolink.com/>

**Comment by isharac** [comment]
@sonia-petrolink 

Thanks for the information provided.

We have fixed an issue in the OAuth application creation flow for tenants in [1].
The relevant issue is [2].
The issue has been fixed in the master branch as well as in APIM-3.2.0

For APIM 3.2.0 we have provided the fix as a wum update and you can obtain it via an active subscription. Please refer [3].

[1] https://github.com/wso2/carbon-identity-framework/pull/3051
[2] https://github.com/wso2/product-is/issues/8369
[3] https://docs.wso2.com/display/updates/Getting+Started

**Comment by sonia-petrolink** [comment]
Hi isharac

Is pure standalone IS 5.10.0 can we use to setup IS as keymanager.
Or IS-KM 5.10.0 is mandatory ? As in document link is for pure standalone for IS as keymanager setup.

Sonia Varshney
Senior Project Lead
Petrolink Services, Inc. | Lulu Tower Info Park | Kochi, Kerala 77092 | INDIA
Office: +04846679678 | Direct: +91 8884888270 | Cell: +91 8884888270| Fax: +04846679678
Email: sonia.varshney@petrolink.com<mailto:sonia.varshney@petrolink.com> | www.petrolink.com<http://www.petrolink.com/>

**Comment by isharac** [comment]
Hi @sonia-petrolink,

You need to use Pure IS 5.10.0 with the APIM 3.2.0
I am afraid if the doc is not clear enough for you, but since APIM 3.2.0 we have completely decoupled the Key manager from the gateway runtime.

Hence we do not need  a separate IS-KM pack now.
We will add a note on the docs.
Thanks.

**Comment by sonia-petrolink** [comment]
Thanks for information. I just want confirm so asked. Document is proper.
If its configuration related changes can I do manaually without took wum update as I cant take right now

Sonia Varshney
Senior Project Lead
Petrolink Services, Inc. | Lulu Tower Info Park | Kochi, Kerala 77092 | INDIA
Office: +04846679678 | Direct: +91 8884888270 | Cell: +91 8884888270| Fax: +04846679678
Email: sonia.varshney@petrolink.com<mailto:sonia.varshney@petrolink.com> | www.petrolink.com<http://www.petrolink.com/>

**Comment by jagadeesha1989** [comment]
Can you please provide the full request for this fix.

**Comment by isharac** [comment]
Please refer 
https://github.com/wso2/carbon-identity-framework/pull/3051

**Comment by isharac** [comment]
Tested with APIM 3.2.0 wum WSO2IS-5.10.0 wum updated packs.
