### ISSUE TITLE
Analytics email alters issue (APIM 3.2.0)

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#1481]
Hi 
we want to get alters for other than gmail domain, so we configured  worker yaml as below 
extension:
        name: email
        namespace: sink
        properties:
          username: **.machine@***.com
          address: **.machine@**.com
          password: Tw3ePoP!
          mail.smtp.host: smtp-mail.outlook.com
          port: 587
          ssl.enable : false
          auth : false
          mail.store.protocol: pop3

But getting below error

 ERROR {io.siddhi.core.stream.output.StreamCallback} - Error on sending events [Event{timestamp=1606819960309, data=[FrequentTierLimitHitting, The application DefaultApplication owned by pritigoyal06@gmail.com@carbon.super frequently goes beyond the allocated quota when accessing the PizzaShackAPI API., 2020-12-01 10:53:19, pritigoyal06@gmail.com,a.shahrozz@gmail.com], isE
[2020-12-01 10:53:19,539] ERROR {io.siddhi.core.stream.output.StreamCallback} - Error on sending events [Event{timestamp=1606819960309, data=[FrequentTierLimitHitting, The application DefaultApplication owned by pritigoyal06@gmail.com@carbon.super frequently goes beyond the allocated quota when accessing the PizzaShackAPI API., 2020-12-01 10:53:19, pritigoyal06@gmail.com,a.shahrozz@gmail.com], isExpired=false}, Event{timestamp=1606819960309, data=[FrequentTierLimitHitting, The application DefaultApplication owned by pritigoyal06@gmail.com@carbon.super frequently goes beyond the allocated quota when accessing the PizzaShackAPI API., 2020-12-01 10:53:19, vivek.kale@**.com], isExpired=false}] in the SiddhiApp 'APIM_ALERT_EMAIL_NOTIFICATION' java.lang.RuntimeException: Error is encountered while sending the message by the email ClientConnector with properties: {From=****@**.com, To=pritigoyal06@gmail.com,a.shahrozz@gmail.com, Subject=Alerts from WSO2 APIM Analytics, Content-Type=text/html}

10:53:19
at io.siddhi.extension.io.email.sink.EmailSink.publish(EmailSink.java:559)

10:53:19
at io.siddhi.core.stream.output.sink.Sink.publish(Sink.java:182)

10:53:19
at io.siddhi.extension.map.text.sinkmapper.TextSinkMapper.mapAndSend(TextSinkMapper.java:264)

10:53:19
at io.siddhi.core.stream.output.sink.SinkMapper.mapAndSend(SinkMapper.java:143)

10:53:19
at io.siddhi.core.stream.output.sink.SinkCallback.receive(SinkCallback.java:68)

10:53:19
at io.siddhi.core.stream.output.StreamCallback.receiveEvents(StreamCallback.java:122)

10:53:19
at io.siddhi.core.stream.output.StreamCallback.receive(StreamCallback.java:102)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)

10:53:19
at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)

10:53:19
at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)

10:53:19
at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)

10:53:19
at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)

10:53:19
at io.siddhi.core.query.processor.filter.FilterProcessor.process(FilterProcessor.java:56)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:116)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)

10:53:19
at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)

10:53:19
at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)

10:53:19
at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)

10:53:19
at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)

10:53:19
at io.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:161)

10:53:19
at io.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:141)

10:53:19
at io.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:55)

10:53:19
at io.siddhi.core.query.processor.stream.window.SlidingWindowProcessor.processEventChunk(SlidingWindowProcessor.java:69)

10:53:19
at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132)

10:53:19
at io.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:170)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:128)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:199)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:474)

10:53:19
at io.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)

10:53:19
at io.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:45)

10:53:19
at io.siddhi.core.stream.input.InputHandler.send(InputHandler.java:78)

10:53:19
at io.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35)

10:53:19
at io.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:81)

10:53:19
at io.siddhi.core.stream.input.source.PassThroughSourceMapper.mapAndProcess(PassThroughSourceMapper.java:66)

10:53:19
at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:152)

10:53:19
at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:118)

10:53:19
at io.siddhi.core.stream.input.source.InMemorySource$1.onMessage(InMemorySource.java:80)

10:53:19
at io.siddhi.core.util.transport.InMemoryBroker$MessageBroker.broadcast(InMemoryBroker.java:110)

10:53:19
at io.siddhi.core.util.transport.InMemoryBroker$MessageBroker.publish(InMemoryBroker.java:118)

10:53:19
at io.siddhi.core.util.transport.InMemoryBroker.publish(InMemoryBroker.java:41)

10:53:19
at io.siddhi.core.stream.output.sink.InMemorySink.publish(InMemorySink.java:109)

10:53:19
at io.siddhi.core.stream.output.sink.Sink.publish(Sink.java:182)

10:53:19
at io.siddhi.core.stream.output.sink.PassThroughSinkMapper.mapAndSend(PassThroughSinkMapper.java:74)

10:53:19
at io.siddhi.core.stream.output.sink.SinkMapper.mapAndSend(SinkMapper.java:180)

10:53:19
at io.siddhi.core.stream.output.sink.SinkCallback.receive(SinkCallback.java:55)

10:53:19
at io.siddhi.core.stream.output.StreamCallback.receive(StreamCallback.java:100)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)

10:53:19
at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)

10:53:19
at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)

10:53:19
at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)

10:53:19
at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:116)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)

10:53:19
at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)

10:53:19
at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)

10:53:19
at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)

10:53:19
at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)

10:53:19
at io.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:161)

10:53:19
at io.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:141)

10:53:19
at io.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:55)

10:53:19
at io.siddhi.core.query.processor.stream.window.SlidingWindowProcessor.processEventChunk(SlidingWindowProcessor.java:69)

10:53:19
at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132)

10:53:19
at io.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:170)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:116)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)

10:53:19
at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)

10:53:19
at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)

10:53:19
at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)

10:53:19
at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)

10:53:19
at io.siddhi.core.query.processor.stream.window.TimeWindowProcessor.process(TimeWindowProcessor.java:168)

10:53:19
at io.siddhi.core.query.processor.stream.window.TimeWindowProcessor.process(TimeWindowProcessor.java:58)

10:53:19
at io.siddhi.core.query.processor.stream.window.SlidingWindowProcessor.processEventChunk(SlidingWindowProcessor.java:69)

10:53:19
at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132)

10:53:19
at io.siddhi.core.query.input.stream.single.EntryValveProcessor.process(EntryValveProcessor.java:49)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)

10:53:19
at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:116)

10:53:19
at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)

10:53:19
at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)

10:53:19
at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)

10:53:19
at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)

10:53:19
at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)

10:53:19
at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)

10:53:19
at io.siddhi.core.query.processor.stream.window.TimeBatchWindowProcessor.process(TimeBatchWindowProcessor.java:339)

10:53:19
at io.siddhi.core.query.processor.stream.window.TimeBatchWindowProcessor.process(TimeBatchWindowProcessor.java:60)

10:53:19
at io.siddhi.core.query.processor.stream.window.BatchingWindowProcessor.processEventChunk(BatchingWindowProcessor.java:74)

10:53:19
at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132)

10:53:19
at io.siddhi.core.query.input.stream.single.EntryValveProcessor.process(EntryValveProcessor.java:49)

10:53:19
at io.siddhi.core.util.Scheduler.sendTimerEvents(Scheduler.java:195)

10:53:19
at io.siddhi.core.util.Scheduler.access$300(Scheduler.java:48)

10:53:19
at io.siddhi.core.util.Scheduler$EventCaller.run(Scheduler.java:294)

10:53:19
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

10:53:19
at java.util.concurrent.FutureTask.run(FutureTask.java:266)

10:53:19
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

10:53:19
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

10:53:19
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

10:53:19
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

10:53:19
at java.lang.Thread.run(Thread.java:748)
	at java.lang.Thread.run(Thread.java:748)

10:53:19
Caused by: org.wso2.transport.email.exception.EmailConnectorException: Error is encountered while sending the message.530 5.7.0 Must issue a STARTTLS command first. w21sm2139321wmi.29 - gsmtp
Caused by: org.wso2.transport.email.exception.EmailConnectorException: Error is encountered while sending the message.530 5.7.0 Must issue a STARTTLS command first. w21sm2139321wmi.29 - gsmtp

10:53:19
at org.wso2.transport.email.client.connector.EmailClientConnectorImpl.send(EmailClientConnectorImpl.java:192)

10:53:19
at io.siddhi.extension.io.email.sink.EmailSink.publish(EmailSink.java:546)

10:53:19
... 110 more

10:53:19
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. w21sm2139321wmi.29 - gsmtp
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. w21sm2139321wmi.29 - gsmtp

10:53:19
at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2267)

10:53:19
at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1758)

10:53:19
at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1257)

10:53:19
at org.wso2.transport.email.client.connector.EmailClientConnectorImpl.send(EmailClientConnectorImpl.java:189)

10:53:19
... 111 more

**Comment by kalevivek11** [comment]
If we do change below

extension:
name: email
namespace: sink
properties:
username: .machine@*.com
address: .machine@.com
password: Tw3ePoP!
mail.smtp.host: smtp-mail.outlook.com
port: 587
ssl.enable : **true**
auth : **true**
mail.store.protocol: pop3

getting Error

Error on 'APIM_ALERT_EMAIL_NOTIFICATION'. Error is encountered while connecting to the the smtp server.Error is encountered while creating the connection using the session.Could not connect to SMTP host: smtp.gmail.com, port: 587, error while connecting at Sink 'email' at 'EmailNotificationStream'. java.lang.RuntimeException: Error is encountered while connecting to the the smtp server.Error is encountered while creating the connection using the session.Could not connect to SMTP host: smtp.gmail.com, port: 587

**Comment by RAVEENSR** [comment]
Duplicate issue. Hence closing. Track the progress of this issue in 1479.
