### ISSUE TITLE
BundleException: Could not resolve module: siddhi-store-elasticsearch -  Unresolved requirement: Import-Package: org.apache.logging.log4j.core

### ISSUE THREAD

**Issue by Manasha11** [wso2/analytics-apim#1525]
**Description:**
When updated to U2 level 17 and the server is started the following error is observed.
```
INFO {org.wso2.carbon.databridge.agent.internal.DataAgentDS} - Successfully deployed Agent Server 
org.osgi.framework.BundleException: Could not resolve module: siddhi-store-elasticsearch [144]
 Unresolved requirement: Import-Package: org.apache.logging.log4j.core
 
 at org.eclipse.osgi.container.Module.start(Module.java:444)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
 at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:453)
 at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
 at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
 at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
 at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
 at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
 at org.eclipse.osgi.container.Module.doStart(Module.java:581)
 at org.eclipse.osgi.container.Module.start(Module.java:449)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
 at org.wso2.carbon.launcher.CarbonServer.loadInitialBundles(CarbonServer.java:242)
 at org.wso2.carbon.launcher.CarbonServer.start(CarbonServer.java:83)
 at org.wso2.carbon.launcher.Main.main(Main.java:84)
```

**Affected Product Version:**
APIM Analytics 2.6.0

**Steps to reproduce:**

1. Update the APIM Analytics 2.6.0.
2. Start the server and observe the above error.

**Comment by Chamindu36** [comment]
Fixed with the latest APIM Analytics 2.6.0 release.
