### ISSUE TITLE
Forget me tool is not working as expected

### ISSUE THREAD

**Issue by chalitha87** [wso2/analytics-apim#491]
**Description:**
Backend gives a null pointer when running the forget me tool in 2.2.0 pack

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/latest apim analytics

**Affected Product Version:**
Latest APIM analytics pack build from jenkins

**OS, DB, other environment details and versions:**   
OS-Mac high sierra
statDB-Mysql
otherDB-H2
JDK-1.8.0_52
Latest APIM analytics jenkins build(16/03/2018)
APIM latest pack (16/03/2018)

**Steps to reproduce:**
Configure analytics and APIM as described in [1].
create and invoke an API.
Configure forgetme tool required configuration as stated in [2]
Ran the forgetme tool for subscribed user.
Backend gives following error.

[1] https://docs.wso2.com/display/AM2xx/Configuring+APIM+Analytics
[2] https://docs.wso2.com/display/AM2xx/Removing+References+to+Deleted+User+Identities

<img width="628" alt="screen shot 2018-03-16 at 4 33 47 pm" src="https://user-images.githubusercontent.com/14923354/37517583-f5784340-2937-11e8-901c-56a647fa8d72.png">

<img width="862" alt="screen shot 2018-03-16 at 4 34 08 pm" src="https://user-images.githubusercontent.com/14923354/37517624-1279593e-2938-11e8-82b7-edd4969d6137.png">

<img width="1174" alt="screen shot 2018-03-16 at 4 36 39 pm" src="https://user-images.githubusercontent.com/14923354/37517724-5500497a-2938-11e8-9927-d74e19e4f1a9.png">

**Results:**
Forget me tool throws the following error.
`2018-03-16 16:21:35 INFO  ForgetMeTool:168 - Generating pseudonym as pseudo name is not provided : 53b5cd5b-faf1-42d6-8b46-2dea1d4d7e30
2018-03-16 16:21:37 INFO  IndexNodeCoordinator:634 - My Analytics Node ID: 86ad0d14-b634-4c4c-b4bc-fb6ee2fa5738
2018-03-16 16:21:37 INFO  IndexNodeCoordinator:794 - Indexing Initialized: STANDALONE | Current Node Indexing: No
2018-03-16 16:21:37 INFO  AnalyticsDataServiceImpl:228 - Current Node Data Purging: Yes
2018-03-16 16:21:37 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@6295d394
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:189)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:129)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.privacy.forgetme.analytics.streams.instructions.AnalyticsStreamsInstruction.filterRecords(AnalyticsStreamsInstruction.java:146)
	at org.wso2.carbon.privacy.forgetme.analytics.streams.instructions.AnalyticsStreamsInstruction.execute(AnalyticsStreamsInstruction.java:93)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:216)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:187)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-03-16 16:21:37 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down
`

**Comment by fazlan-nazeem** [comment]
This has caused due to an issue in the documentation. This has been fixed now.
