### ISSUE TITLE
Issue in APIM_ABNORMAL_REQUEST_PATTERN 

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/analytics-apim#570]
Following Exception is thrown in markov:markovChain() extension

`[2018-08-30 09:44:30,226] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} - Error in passing event eventList [
Event{
  streamId='org.wso2.apimgt.statistics.request:3.0.0',
  timeStamp=1535602470222,
  metaData=[PRODUCTION],
  correlationData=[],
  payloadData=[ZkfE2oUYRYrWMibpPk_1I5TdLkka, tca, 2, admin, /pizzashack/1.0.0, PizzaShackAPI, 1.0.0, /menu, /menu, GET, admin, carbon.super, Unlimited, 192.168.56.1, admin@carbon.super, carbon.super, 192.168.56.1, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36, 1535602470218, false, 4, 0, 4, false, 0, https-8243, 200, https://localhost:9443/am/sample/pizzashack/v1/api/, 0, 0, 0, 0, 4, 0, SYNAPSE, Synapse],
  arbitraryDataMap=null,
}
] to subscriber org.wso2.extension.siddhi.io.wso2event.source.AgentCallbackImpl@7d1ef263 java.lang.IncompatibleClassChangeError: Found class org.wso2.siddhi.core.util.timestamp.TimestampGenerator, but interface was expected
	at org.wso2.extension.siddhi.execution.markov.MarkovChainStreamProcessor.process(MarkovChainStreamProcessor.java:266)
	at org.wso2.siddhi.core.query.processor.stream.StreamProcessor.processEventChunk(StreamProcessor.java:47)
	at org.wso2.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:125)
	at org.wso2.siddhi.core.query.input.stream.single.EntryValveProcessor.process(EntryValveProcessor.java:50)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:186)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:96)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:121)
	at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:156)
	at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:375)
	at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
	at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
`

**Comment by chamilaadhi** [comment]
fixed with component upgrade in https://github.com/wso2/analytics-apim/pull/571
