### ISSUE TITLE
[2.1.0 Analytics] Incorrect error log when publishing events without appending '@carbon.super' to the user name in a email username enabled Analytics server

### ISSUE THREAD

**Issue by chalitha1989** [wso2/analytics-apim#583]
**Description:**

The analytic log says admin connected although the user name is wrong.

_APIM config_

           <DASServerURL>{tcp://10.172.10.50:7611}</DASServerURL>
        
        <DASUsername>admind@gmail.com</DASUsername>
        
        <DASPassword>XXXXX</DASPassword>

_APIM Log_

TID: [-1] [] [2018-09-13 00:46:09,161] ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} -  Error while trying to connect to the endpoint. Cannot borrow client for ssl://10.1733.10.50:7711. {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker}
org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://10.172.10.50:7711.
    at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:131)
    at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Error while trying to login to the data receiver.
    at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:54)
    at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:125)
    ... 6 more
Caused by: org.apache.thrift.transport.TTransportException
    at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
    at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
    at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
    at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
    at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
    at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.recv_connect(ThriftSecureEventTransmissionService.java:110)
    at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.connect(ThriftSecureEventTransmissionService.java:96)
    at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:47)
    ... 7 more

_Analytics Log_

TID: [-1234] [] [2018-09-13 01:12:39,156]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user **admind@google.com** connected {org.wso2.carbon.databridge.core.DataBridge}
TID: [-1234] [] [2018-09-13 01:12:39,161] ERROR {org.apache.thrift.server.TThreadPoolServer} -  Thrift error occurred during processing of message. {org.apache.thrift.server.TThreadPoolServer}
org.apache.thrift.protocol.TProtocolException: Required field 'message' was not present! Struct: ThriftAuthenticationException(message:null)
    at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException.validate(ThriftAuthenticationException.java:285)
    at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException$ThriftAuthenticationExceptionStandardScheme.write(ThriftAuthenticationException.java:344)
    at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException$ThriftAuthenticationExceptionStandardScheme.write(ThriftAuthenticationException.java:312)
    at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException.write(ThriftAuthenticationException.java:263)
    at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.write(ThriftSecureEventTransmissionService.java:2049)
    at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.write(ThriftSecureEventTransmissionService.java:1998)
    at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result.write(ThriftSecureEventTransmissionService.java:1944)
    at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:53)
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
    at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
TID: [-1234] [] [2018-09-13 01:12:39,161]  WARN {org.apache.thrift.transport.TIOStreamTransport} -  Error closing output stream. {org.apache.thrift.transport.TIOStreamTransport}
java.net.SocketException: Socket is closed
    at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1542)
    at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1563)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
    at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
    at org.apache.thrift.transport.TSocket.close(TSocket.java:196)
    at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Suggested Labels:**
improvement
**Suggested Assignees:**
NA

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
NA

**Steps to reproduce:**
1. Enable email user name in analytics and apim.
2. Configure user name of DASServerURL without appending the super tenant domain. ex: abcadmin@gmail.com
3. publish events to analytics server.

**Related Issues:**
NA

**Comment by lendldigia** [comment]
Any update on this ? I am getting the same error after I have configured email (username changed from admin to admin@wso2.com in user-mgt.xml file) as the username. I was actually enabling SSO on WSO2 via Microsoft AD and the SSO part is working but it broke the working analytics. 
Note: I did not make changes in the analytics image (tried making the same user-mgt.xml change for analytics) but that did not work and still get the exact same errros in APIM and Analytics.

**Comment by SureshG02** [comment]
@chalitha1989 Do you mean this error is not coming when you append username with '@carbon.super' ? For me I tried both username appended with '@carbon.super' and without in both case its failing. When I am trying with username admin@wso2.com@carbon.super Analytics log gives below error :
Analytics log:
TID: [-1234] [] [2019-01-02 11:55:33,464]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user admin@wso2.com@carbon.super connected {org.wso2.carbon.databridge.core.DataBridge}
TID: [-1234] [] [2019-01-02 11:55:33,464] ERROR {org.wso2.carbon.identity.authentication.AuthenticationServiceImpl} -  Invalid User : admin@wso2.com {org.wso2.carbon.identity.authentication.AuthenticationServiceImpl}
TID: [-1234] [] [2019-01-02 11:55:33,464] ERROR {org.apache.thrift.server.TThreadPoolServer} -  Thrift error occurred during processing of message. {org.apache.thrift.server.TThreadPoolServer}
org.apache.thrift.protocol.TProtocolException: Required field 'message' was not present! Struct: ThriftAuthenticationException(message:null)
        at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException.validate(ThriftAuthenticationException.java:285)
        at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException$ThriftAuthenticationExceptionStandardScheme.write(ThriftAuthenticationException.java:344)
        at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException$ThriftAuthenticationExceptionStandardScheme.write(ThriftAuthenticationException.java:312)
        at org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException.write(ThriftAuthenticationException.java:263)
        at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.write(ThriftSecureEventTransmissionService.java:2049)
        at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.write(ThriftSecureEventTransmissionService.java:1998)
        at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result.write(ThriftSecureEventTransmissionService.java:1944)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:53)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
TID: [-1234] [] [2019-01-02 11:55:33,465]  WARN {org.apache.thrift.transport.TIOStreamTransport} -  Error closing output stream. {org.apache.thrift.transport.TIOStreamTransport}
java.net.SocketException: Socket is closed
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1542)
        at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1563)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
        at org.apache.thrift.transport.TSocket.close(TSocket.java:196)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

And when username is admin@wso2.com then Analytics log is giving exactly same log what you have mentioned.

**Comment by ruks** [comment]
APIM Analytics(2.1.0) used the same User Store as APIM and analytics. But now, from Analytics 2.6.0(SP based), worker used local IDP configuration. With local IDP configuration, a username format can be defined as preferred and when to authenticate, it considers as plain text. 
Hence this is not relevant closing.
