### ISSUE TITLE
[API Analytics 2.6] [MSSQL] Malformed syntax of query "store_select_query_ApiUserPerAppAgg_SECONDS": Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by robertociuccigiuliani** [wso2/analytics-apim#607]
**Description:**
I integrated API Manager 2.6 with API Analytics 2.6 in only mode "worker" to manage and look the statistics provided by dashboards from the Publisher and the Store.
But in API Analytics 2.6 based on the new Stream Processor I register an exception of malformed syntax of query in MSSQL Server:
`
[2019-04-17 19:15:22,739] ERROR {org.wso2.carbon.siddhi.store.api.rest.impl.StoresApiServiceImpl} - Error while querying for siddhiApp: APIM_ACCESS_SUMMARY, with query: from ApiUserPerAppAgg_SECONDS select AGG_TIMESTAMP limit 1; Error: Error executing 'store_select_query_ApiUserPerAppAgg_SECONDS', Error when executing query: 'SELECT ApiUserPerAppAgg_SECONDS.AGG_TIMESTAMP AS AGG_TIMESTAMP FROM ApiUserPerAppAgg_SECONDS FETCH NEXT 1 ROWS ONLY' on 'ApiUserPerAppAgg_SECONDS' store: Invalid usage of the option NEXT in the FETCH statement. org.wso2.siddhi.core.exception.StoreQueryCreationException: Error executing 'store_select_query_ApiUserPerAppAgg_SECONDS', Error when executing query: 'SELECT ApiUserPerAppAgg_SECONDS.AGG_TIMESTAMP AS AGG_TIMESTAMP FROM ApiUserPerAppAgg_SECONDS FETCH NEXT 1 ROWS ONLY' on 'ApiUserPerAppAgg_SECONDS' store: Invalid usage of the option NEXT in the FETCH statement.
`

**Suggested Labels:**
APIM 2.6.0
API Analytics 2.6.0
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6
API Analytics 2.6.0 ( WSO2 Stream Processor 4.3.0 )

**OS, DB, other environment details and versions:**    
OS: Red Hat 7.4
DB: Microsoft SQL Server 2017
JDBC Driver: mssql-jdbc-7.0.0.jre8.jar
JDK & JRE: Oracle jdk1.8.0_161

**Steps to reproduce:**
1) Integrate API Manager with API Analytics according to the wso2 guidelines 
2) Start API Manager and API Analytics
3) Lookup dashboard view of API Manager for statistics 
4) The API Manager dashboards do not show any statistics, as if it were not configured correctly
5) In carbon.log of the API Analytics in worker mode shows the following exception (malformed syntax of query launched):
`
[2019-04-17 19:15:22,739] ERROR {org.wso2.carbon.siddhi.store.api.rest.impl.StoresApiServiceImpl} - Error while querying for siddhiApp: APIM_ACCESS_SUMMARY, with query: from ApiUserPerAppAgg_SECONDS select AGG_TIMESTAMP limit 1; Error: Error executing 'store_select_query_ApiUserPerAppAgg_SECONDS', Error when executing query: 'SELECT ApiUserPerAppAgg_SECONDS.AGG_TIMESTAMP AS AGG_TIMESTAMP FROM ApiUserPerAppAgg_SECONDS FETCH NEXT 1 ROWS ONLY' on 'ApiUserPerAppAgg_SECONDS' store: Invalid usage of the option NEXT in the FETCH statement. org.wso2.siddhi.core.exception.StoreQueryCreationException: Error executing 'store_select_query_ApiUserPerAppAgg_SECONDS', Error when executing query: 'SELECT ApiUserPerAppAgg_SECONDS.AGG_TIMESTAMP AS AGG_TIMESTAMP FROM ApiUserPerAppAgg_SECONDS FETCH NEXT 1 ROWS ONLY' on 'ApiUserPerAppAgg_SECONDS' store: Invalid usage of the option NEXT in the FETCH statement.
	at org.wso2.siddhi.core.SiddhiAppRuntime.query(SiddhiAppRuntime.java:310)
	at org.wso2.siddhi.core.SiddhiAppRuntime.query(SiddhiAppRuntime.java:273)
	at org.wso2.carbon.siddhi.store.api.rest.impl.StoresApiServiceImpl.query(StoresApiServiceImpl.java:66)
	at org.wso2.carbon.siddhi.store.api.rest.StoresApi.query(StoresApi.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.siddhi.core.exception.StoreQueryRuntimeException: Error executing 'store_select_query_ApiUserPerAppAgg_SECONDS', Error when executing query: 'SELECT ApiUserPerAppAgg_SECONDS.AGG_TIMESTAMP AS AGG_TIMESTAMP FROM ApiUserPerAppAgg_SECONDS FETCH NEXT 1 ROWS ONLY' on 'ApiUserPerAppAgg_SECONDS' store: Invalid usage of the option NEXT in the FETCH statement.
	at org.wso2.siddhi.core.query.SelectStoreQueryRuntime.execute(SelectStoreQueryRuntime.java:68)
	at org.wso2.siddhi.core.SiddhiAppRuntime.query(SiddhiAppRuntime.java:303)
	... 14 more
Caused by: org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Error when executing query: 'SELECT ApiUserPerAppAgg_SECONDS.AGG_TIMESTAMP AS AGG_TIMESTAMP FROM ApiUserPerAppAgg_SECONDS FETCH NEXT 1 ROWS ONLY' on 'ApiUserPerAppAgg_SECONDS' store: Invalid usage of the option NEXT in the FETCH statement.
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.query(RDBMSEventTable.java:1605)
	at org.wso2.siddhi.core.table.record.AbstractQueryableRecordTable.query(AbstractQueryableRecordTable.java:90)
	at org.wso2.siddhi.core.query.SelectStoreQueryRuntime.execute(SelectStoreQueryRuntime.java:55)
	... 15 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid usage of the option NEXT in the FETCH statement.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:434)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeQuery(HikariPreparedStatementProxy.java)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.query(RDBMSEventTable.java:1593)
	... 17 more
`

[carbon-04-17-2019.log](https://github.com/wso2/analytics-apim/files/3095054/carbon-04-17-2019.log)

**Comment by robertociuccigiuliani** [comment]
Sry target DB is : Microsoft SQL Server 2017, not 2016 version

**Comment by thetemplateblog** [comment]
Did you ever find a solution for this?

**Comment by robertociuccigiuliani** [comment]
Yes, i used not patched version of analytic-apim, only used from download
refered to site WSO2 official, not github version.

**Comment by ruks** [comment]
@RAVEENSR Can you check is this reproducible when you test with MSSQL?

**Comment by RAVEENSR** [comment]
Related issue in Siddhi-Store-RDBMS is https://github.com/siddhi-io/siddhi-store-rdbms/issues/156 and this issue is fixed in the latest siddhi-store-rdbms versions both in 4.xx and 5.xx versions.
