### ISSUE TITLE
Warning when invoking APIs in WSO2 API Manager

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/analytics-apim#663]
**Description:**
A warning appears when invoking an API when worker.sh is running, stating an issue with some siddhi queries.

The error log is shown below:

```
[2019-09-26 21:04:59,749]  WARN {io.siddhi.core.query.input.stream.join.JoinProcessor} - Performing select clause in databases failed due to 'Error when preparing to execute query: 'SELECT ? AS apiContext, ? AS apiName, ? AS apiVersion, ? AS apiCreator, ? AS apiCreatorTenantDomain, ? AS applicationOwner, ? AS lastAccessTime FROM ApiLastAccessSummary WHERE (((? = ApiLastAccessSummary.apiName ) AND  (? = ApiLastAccessSummary.apiCreatorTenantDomain )) AND  (? = ApiLastAccessSummary.apiCreator )) HAVING ((? >= lastAccessTime )OR lastAccessTime IS NULL )' on 'ApiLastAccessSummary' in query 'Filter events to check latest timestamp' within Siddhi app 'APIM_ACCESS_SUMMARY' hence reverting back to querying only with where clause. io.siddhi.extension.store.rdbms.exception.RDBMSTableException: Error when preparing to execute query: 'SELECT ? AS apiContext, ? AS apiName, ? AS apiVersion, ? AS apiCreator, ? AS apiCreatorTenantDomain, ? AS applicationOwner, ? AS lastAccessTime FROM ApiLastAccessSummary WHERE (((? = ApiLastAccessSummary.apiName ) AND  (? = ApiLastAccessSummary.apiCreatorTenantDomain )) AND  (? = ApiLastAccessSummary.apiCreator )) HAVING ((? >= lastAccessTime )OR lastAccessTime IS NULL )' on 'ApiLastAccessSummary'
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.query(RDBMSEventTable.java:1832)
	at io.siddhi.core.table.record.AbstractQueryableRecordTable.query(AbstractQueryableRecordTable.java:691)
	at io.siddhi.core.query.processor.stream.window.TableWindowProcessor.query(TableWindowProcessor.java:103)
	at io.siddhi.core.query.input.stream.join.JoinProcessor.query(JoinProcessor.java:179)
	at io.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:108)
	at io.siddhi.core.query.processor.stream.window.LengthBatchWindowProcessor.process(LengthBatchWindowProcessor.java:186)
	at io.siddhi.core.query.processor.stream.window.LengthBatchWindowProcessor.process(LengthBatchWindowProcessor.java:57)
	at io.siddhi.core.query.processor.stream.window.BatchingWindowProcessor.processEventChunk(BatchingWindowProcessor.java:74)
	at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132)
	at io.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:170)
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:116)
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)
	at io.siddhi.core.query.output.ratelimit.time.LastGroupByPerTimeOutputRateLimiter.process(LastGroupByPerTimeOutputRateLimiter.java:99)
	at io.siddhi.core.util.Scheduler.sendTimerEvents(Scheduler.java:195)
	at io.siddhi.core.util.Scheduler.access$300(Scheduler.java:48)
	at io.siddhi.core.util.Scheduler$EventCaller.run(Scheduler.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Column "LASTACCESSTIME" must be in the GROUP BY list; SQL statement:
SELECT ? AS apiContext, ? AS apiName, ? AS apiVersion, ? AS apiCreator, ? AS apiCreatorTenantDomain, ? AS applicationOwner, ? AS lastAccessTime FROM ApiLastAccessSummary WHERE (((? = ApiLastAccessSummary.apiName ) AND  (? = ApiLastAccessSummary.apiCreatorTenantDomain )) AND  (? = ApiLastAccessSummary.apiCreator )) HAVING ((? >= lastAccessTime )OR lastAccessTime IS NULL ) [90016-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.getValue(ExpressionColumn.java:189)
	at org.h2.expression.Comparison.getValue(Comparison.java:237)
	at org.h2.expression.ConditionAndOr.getValue(ConditionAndOr.java:86)
	at org.h2.command.dml.Select.queryGroup(Select.java:364)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:620)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)
	at org.h2.command.dml.Query.query(Query.java:371)
	at org.h2.command.dml.Query.query(Query.java:333)
	at org.h2.command.CommandContainer.query(CommandContainer.java:113)
	at org.h2.command.Command.executeQuery(Command.java:201)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:329)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
	at java.lang.Thread.run(Thread.java:748)

	at org.h2.engine.SessionRemote.done(SessionRemote.java:629)
	at org.h2.command.CommandRemote.executeQuery(CommandRemote.java:176)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:111)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeQuery(HikariPreparedStatementProxy.java)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.query(RDBMSEventTable.java:1815)
	... 27 more
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0
**OS, DB, other environment details and versions:**    
Ubuntu 18.04.2 LTS, testing with 3.0.0 Alpha pack of WSO2 API Manager

**Related Issues:**

**Comment by RAVEENSR** [comment]
Fixed in https://github.com/wso2/analytics-apim/pull/720
