### ISSUE TITLE
Business rules component does not support PostgreSQL

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/analytics-apim#820]
**Description:**
Business rules component does not have the support for PostgreSQL.

Gives the following error:

```
[2019-11-21 14:15:10,362]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.ExceptionInInitializerError
	at org.wso2.carbon.business.rules.core.datasource.QueryExecutor.<init>(QueryExecutor.java:54)
	at org.wso2.carbon.business.rules.core.services.TemplateManagerService.<init>(TemplateManagerService.java:75)
	at org.wso2.carbon.business.rules.core.bean.TemplateManagerInstance.<clinit>(TemplateManagerInstance.java:36)
	at org.wso2.carbon.business.rules.core.api.impl.BusinessRulesApiServiceImpl.getBusinessRules(BusinessRulesApiServiceImpl.java:197)
	at org.wso2.carbon.business.rules.core.api.BusinessRulesApi.getBusinessRules(BusinessRulesApi.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$0(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.business.rules.core.exceptions.BusinessRulesDatasourceInitializationException: Error initializing connection. 
	at org.wso2.carbon.business.rules.core.datasource.DataSourceServiceProvider.initConnection(DataSourceServiceProvider.java:82)
	at org.wso2.carbon.business.rules.core.datasource.DataSourceServiceProvider.<init>(DataSourceServiceProvider.java:51)
	at org.wso2.carbon.business.rules.core.datasource.DataSourceServiceProvider.<clinit>(DataSourceServiceProvider.java:45)
	... 16 more
Caused by: org.wso2.carbon.database.query.manager.exception.QueryMappingNotAvailableException: Unable to load queries.
	at org.wso2.carbon.business.rules.core.datasource.QueryManager.readConfigs(QueryManager.java:70)
	at org.wso2.carbon.business.rules.core.datasource.QueryManager.<init>(QueryManager.java:48)
	at org.wso2.carbon.business.rules.core.datasource.DataSourceServiceProvider.initConnection(DataSourceServiceProvider.java:80)
	... 18 more
Caused by: org.wso2.carbon.database.query.manager.exception.QueryMappingNotAvailableException: Mapping value for query: 'CHECK_FOR_BUSINESS_RULES_TABLE' not found in Deployment config Map and Component config Map for database type: 'PostgreSQL' and version '9.5.19'.
	at org.wso2.carbon.database.query.manager.QueryProvider.mergeMapping(QueryProvider.java:105)
	at org.wso2.carbon.business.rules.core.datasource.QueryManager.readConfigs(QueryManager.java:65)
	... 20 more
```

According to [this](https://docs.wso2.com/display/SP440/Configuring+Datasources#ConfiguringDatasources-BusinessRulesBusinessRules) Business rules does not have the support for Postgresql. To add the support mappings for Postgresql should be provided in [here](https://github.com/wso2/carbon-analytics/blob/373d200b214dd80b5b3e341e4b35b1ad652d8e2f/components/org.wso2.carbon.business.rules.core/src/main/resources/queries.yaml).

**Suggested Labels:**
Bug, Improvement

**Suggested Assignees:**

**Affected Product Version:**
APIM Analytics 3.0.0
 
**OS, DB, other environment details and versions:**    
Mac Os Catalina, PostgreSQL 9.5

**Steps to reproduce:**
Point the Business Rules DB to a postgresql DB and try to access `https://localhost:9643/business-rules/`

**Related Issues:**

**Comment by RAVEENSR** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1764.
