### ISSUE TITLE
Print user friendly error message on UI

### ISSUE THREAD

**Issue by erangatl** [wso2/analytics-apim#881]
**Description:**
![image](https://user-images.githubusercontent.com/20179540/70903295-9c374200-2024-11ea-93f0-2677041b6e8b.png)

**Comment by ruwiniwj** [comment]
Shall we add the error stack trace as well?

**Comment by erangatl** [comment]
`[2019-12-17 09:42:23,965]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 API Manager Analytics Server started in 2.973 sec
[2019-12-17 09:42:35,147]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 19 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at feign.gson.GsonDecoder.decode(GsonDecoder.java:55)
	at org.wso2.analytics.apim.rest.api.proxy.impl.ApimApiServiceImpl.apimApisGet(ApimApiServiceImpl.java:71)
	at org.wso2.analytics.apim.rest.api.proxy.ApimApi.apimApisGet(ApimApi.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 19 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 16 more`

**Comment by ruwiniwj** [comment]
This happens because the REST API call from APIM analytics server to APIM server to retrieve the API list returns a response with status code '200' and content-type 'text/html' instead of 'application/json'. As a result an error is thrown when trying to decode the response using GsonDecoder.

**Comment by imchivaa** [comment]
Hi @ruwiniwj ,

I am facing this issue as well. Do you have any solutions for this? Or do we need to wait for m5 release?

Thanks.

**Comment by ruwiniwj** [comment]
@imchivaa this error occurs due to using incompatible APIM and APIM analytics products. Due to a change in APIM REST APIs, from APIM analytics 3.1.0 - M4 onwards, analytics is only compatible with APIM 3.1.0 - M5 onwards releases. 
Please try out APIM analytics 3.1.0 - M4 with APIM 3.1.0 - M5.
