### ISSUE TITLE
Error While display widgets in analytic publisher and developer dashboard

### ISSUE THREAD

**Issue by ashishpilania18** [wso2/analytics-apim#891]
**Description:**

APIM Manager is deployed in distributed architecture with each separate component and analytics has been configured but getting  Error While display widgets in analytic publisher and developer dashboard .Please help

[2019-12-20 15:49:44,098]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 19 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at feign.gson.GsonDecoder.decode(GsonDecoder.java:55)
        at org.wso2.analytics.apim.rest.api.proxy.impl.ApimApiServiceImpl.apimApisGet(ApimApiServiceImpl.java:71)
        at org.wso2.analytics.apim.rest.api.proxy.ApimApi.apimApisGet(ApimApi.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 19 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        ... 16 more

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** wso2am-analytics-3.1.0-m4

**OS, DB, other environment details and versions:**       Linux and Postgres DB

**Steps to reproduce:**

**Related Issues:**

**Comment by RAVEENSR** [comment]
@ashishpilania18 Are you using APIM 3.0.0 version? If yes then you need to use the latest [APIM 3.1.0 milestone](https://github.com/wso2/product-apim/releases/download/v3.1.0-m5/wso2am-3.1.0-m5.zip) which is m5 with the latest released APIM Analytics 3.1.0-m4.

**Comment by ruwiniwj** [comment]
@ashishpilania18  this error occurs due to using incompatible APIM and APIM analytics products. Due to a change in APIM REST APIs, from APIM analytics 3.1.0 - M4 onwards, analytics is only compatible with APIM 3.1.0 - M5 onwards releases.
Please try out APIM analytics 3.1.0 - M4 with APIM 3.1.0 - M5.
