### ISSUE TITLE
org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException: wrong userName or password

### ISSUE THREAD

**Issue by loeb-ift** [wso2/analytics-apim#894]
**Description:**
I had  changed admin password,
After admin's password changed, and work fine on wso2apim product.

Also modify the passwords in the wso2am-analytics-3.1.0-m2/conf/dashboard/deployment.yaml 
and got two errors

1.password wrong
2.ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:7712

env. wso2am-analytics-3.1.0-m2 and wso2AM3.1.0-M5 all in one
ref.  https://www.chakray.com/step-by-step-guide-to-successfully-configure-apim-analytics/

pls help 

[log of wso2am-analytics-3.0.0]
[2020-01-03 01:03:28,852] ERROR {org.wso2.carbon.databridge.core.internal.authentication.CarbonAuthenticationHandler} - Authentication failed for username 'admin'. Error : 'Invalid_Credentials'. Error Description : 'The login credential used for login are invalid, username : 'admin'.'
[2020-01-03 01:03:28,853] ERROR {org.wso2.carbon.databridge.core.internal.authentication.Authenticator} - wrong userName or password
[2020-01-03 01:03:58,865]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
[2020-01-03 01:03:58,865] ERROR {org.wso2.carbon.databridge.core.internal.authentication.CarbonAuthenticationHandler} - Authentication failed for username 'admin'. Error : 'Invalid_Credentials'. Error Description : 'The login credential used for login are invalid, username : 'admin'.'
[2020-01-03 01:03:58,866] ERROR {org.wso2.carbon.databridge.core.internal.authentication.Authenticator} - wrong userName or password
[2020-01-03 01:04:28,845]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
[2020-01-03 01:04:28,846] ERROR {org.wso2.carbon.databridge.core.internal.authentication.CarbonAuthenticationHandler} - Authentication failed for username 'admin'. Error : 'Invalid_Credentials'. Error Description : 'The login credential used for login are invalid, username : 'admin'.'
[2020-01-03 01:04:28,847] ERROR {org.wso2.carbon.databridge.core.internal.authentication.Authenticator} - wrong userName or password
[2020-01-03 01:04:58,850]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected

[log of wso2AM3.1.0-M5]

020-01-03 01:01:28,804]  WARN - DataEndpointGroup No receiver is reachable at reconnection, will try to reconnect every 30 sec
[2020-01-03 01:01:28,957] ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:7712.
org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://localhost:7712.
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:145) ~[org.wso2.carbon.databridge.agent_5.2.16.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59) [org.wso2.carbon.databridge.agent_5.2.16.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Error while trying to login to the data receiver.
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:49) ~[org.wso2.carbon.databridge.agent_5.2.16.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:139) ~[org.wso2.carbon.databridge.agent_5.2.16.jar:?]
	... 6 more
Caused by: org.wso2.carbon.databridge.commons.thrift.exception.ThriftAuthenticationException: wrong userName or password'

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2am-analytics-3.1.0-m2 with wso2am-3.1.0-m5
**OS, DB, other environment details and versions:**    
ubuntu 18.04 
local H2 db

**Steps to reproduce:**
wso2am-analytics-3.1.0-m2
startup sh bin/worker.sh
and then
start wso2am-3.1.0-m5
bin/wso2server.sh

**Related Issues:**

**Comment by ruwiniwj** [comment]
@loeb-ift please note that the APIM 3.1.0 - M5 is compatible is not compatible with releases prior to APIM Analytics 3.1.0-M4. Please use the latest releases APIM 3.1.0 - M5 and APIM Analytics 3.1.0-M4.

> ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:7712

The above error occurs when the APIM server tries to connect to the analytics server. Did you update the admin password in _<ANALYTICS_HOME>/conf/worker/deployment.yaml_ under `auth.configs`?

**Comment by loeb-ift** [comment]
update to  APIM Analytics 3.1.0-M4  and
change the admin password in <ANALYTICS_HOME>/conf/worker/deployment.yaml  encode base64(#NEWPASSWORD) 
it works now!

**Comment by ruwiniwj** [comment]
Great! 
Closing this issue as it is resolved.
