### ISSUE TITLE
wso2 3.0.0 analytics Error while running dashboard

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#906]
Steps to reproduce.
followed the link 
https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#quick-setup

1. start worker
2. start wso2 APIM ALLINONE
3. start dashboard

pFA yaml files

[yamlFiles.zip](https://github.com/wso2/analytics-apim/files/4058921/yamlFiles.zip)

**Description:**
ERROR {org.wso2.carbon.analytics.auth.rest.api.impl.LoginApiServiceImpl} - Error occurred: Connection refused: connect executing POST https://localhost/oauth2/token feign.RetryableException: Connection refused: connect executing POST https://localhost/oauth2/token
        at feign.FeignException.errorExecuting(FeignException.java:67)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:104)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy83.generateAccessToken(Unknown Source)
        at org.wso2.carbon.analytics.idp.client.external.impl.OAuth2ServiceStubs$TokenServiceStub.generateAuthCodeGrantAccessToken(OAuth2ServiceStubs.java:157)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:60)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy83.generateAuthCodeGrantAccessToken(Unknown Source)
        at org.wso2.analytics.apim.idp.client.ApimIdPClient.authCodeLogin(ApimIdPClient.java:470)
        at org.wso2.carbon.analytics.auth.rest.api.impl.LoginApiServiceImpl.loginCallbackAppNameGet(LoginApiServiceImpl.java:257)
        at org.wso2.carbon.analytics.auth.rest.api.LoginApi.loginCallbackAppNameGet(LoginApi.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
        at feign.Client$Default.convertAndSend(Client.java:133)
        at feign.Client$Default.execute(Client.java:73)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
        ... 22 more

**Comment by RAVEENSR** [comment]
By looking at your yaml file I can see that you have incorrectly set the `kmTokenUrl` for the dashboard runtime deployment.yaml file. Please correct the misconfigured `kmTokenUrl:https://localhost/oauth2` to `kmTokenUrl: https://localhost:9443/oauth2` under `auth.configs` .

**Comment by fazlan-nazeem** [comment]
Addressed in #908
