### ISSUE TITLE
Error while starting analytics dashboard related to MSF4j core error using open jdk java 1.8.0_202

### ISSUE THREAD

**Issue by pritigoyal06** [wso2/analytics-apim#944]
**Description:**

Hi team,
I am trying to use Data analytic server of WSO2  3.0 version. Worker is working fine but when i try to start dashboard it gives  below error :
[2020-01-29 11:08:25,121] ERROR {msf4j-core} - [SCR] Error while trying to bind reference Reference[name = microservice, interface = org.wso2.msf4j.Microservice, policy = dynamic, cardinality = 0..n, target = null, bind = addService, unbind = removeService]
        Details:
        Problematic reference = Reference[name = microservice, interface = org.wso2.msf4j.Microservice, policy = dynamic, cardinality = 0..n, target = null, bind = addService, unbind = removeService]
        of service component = org.wso2.msf4j.internal.MicroServicesServerSC
        component implementation class = org.wso2.msf4j.internal.MicroservicesServerSC
        located in bundle with symbolic name = msf4j-core
        bundle location = reference:file:../lib/plugins/msf4j-core_2.7.3.jar java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444)
        at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:482)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:999)
        at org.wso2.carbon.uiserver.internal.deployment.msf4j.MicroservicesRegistrar.register(MicroservicesRegistrar.java:154)
        at org.wso2.carbon.uiserver.internal.deployment.msf4j.MicroservicesRegistrar.lambda$register$3(MicroservicesRegistrar.java:144)
        at org.wso2.carbon.uiserver.internal.deployment.msf4j.MicroservicesRegistrar$$Lambda$283.0000000015BBB520.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:496)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:486)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.carbon.uiserver.internal.deployment.msf4j.MicroservicesRegistrar.register(MicroservicesRegistrar.java:145)
        at org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder.appDeploymentEvent(AppTransportBinder.java:76)
        at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.publishAppDeploymentEvent(ArtifactAppDeployer.java:154)
        at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.deploy(ArtifactAppDeployer.java:103)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine$$Lambda$242.0000000015AA7E30.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
        at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
        at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager$$Lambda$156.00000000132D4700.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NoClassDefFoundError: org.wso2.msf4j.util.RuntimeAnnotations (initialization failure)
        at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96)
        at org.wso2.msf4j.internal.MicroservicesServerSC.addMicroserviceToRegistry(MicroservicesServerSC.java:405)
        at org.wso2.msf4j.internal.MicroservicesServerSC.addService(MicroservicesServerSC.java:105)
        ... 49 more
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: java.lang.Class$Atomic
        at org.wso2.msf4j.util.RuntimeAnnotations.<clinit>(RuntimeAnnotations.java:110)
        at org.wso2.msf4j.internal.MicroservicesServerSC.addMicroserviceToRegistry(MicroservicesServerSC.java:405)
        at org.wso2.msf4j.internal.MicroservicesServerSC.addService(MicroservicesServerSC.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        ... 48 more
Caused by: java.lang.ClassNotFoundException: java.lang.Class$Atomic
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:332)
        at org.wso2.msf4j.util.RuntimeAnnotations.<clinit>(RuntimeAnnotations.java:58)
        ... 52 more

But when i try this with open jdk 11. it not give any error. But I need to use analytic server with Java 8 . 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RAVEENSR** [comment]
What is the Java 8 version you are using?

**Comment by pritigoyal06** [comment]
Hi Team,

Details are below:

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Windows 10 amd64-64-Bit
Compressed References 20190205_265 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)

Thanks and Regards
Priti Goyal

**Comment by RAVEENSR** [comment]
Hi @pritigoyal06 

We do not support OpenJDK with Eclipse OpenJ9. Can you please try with either Oracle JDK with Java HotSpot VM or Open JDK with OpenJDK VM?
